spring:
  application:
    name: billing-service
  datasource:
    url: ${BILLING_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5432/campusenroll}
    username: ${BILLING_SERVICE_DATASOURCE_USERNAME:campus}
    password: ${BILLING_SERVICE_DATASOURCE_PASSWORD:campus_password}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  messaging:
    exchange: ${APP_EVENTS_EXCHANGE:campusenroll.events}
    billing-status-changed-routing-key: ${APP_BILLING_STATUS_CHANGED_ROUTING_KEY:billing.status.changed}
  outbox:
    publisher:
      fixed-delay-ms: ${APP_OUTBOX_PUBLISHER_FIXED_DELAY_MS:5000}
      batch-size: ${APP_OUTBOX_PUBLISHER_BATCH_SIZE:20}
      max-attempts: ${APP_OUTBOX_PUBLISHER_MAX_ATTEMPTS:5}

server:
  port: ${SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
